server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms-route # ��Ʒ����·��
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: oms-route # ��������·��
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route # �û�����·��
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route # �ֿ����·��
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: sms-route # Ӫ������·��
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
